export {default as Home} from './Home'
export {default as About} from './About'
export {default as Features} from './Features'
export {default as Pricing} from './Pricing'
export {default as Premium} from './Premium'